
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE = 'XSMALL';
CREATE DATABASE IF NOT EXISTS RETAIL_DWH;

USE DATABASE RETAIL_DWH;
CREATE SCHEMA STAGE;
CREATE SCHEMA CORE; 
CREATE SCHEMA MART;  
CREATE SCHEMA UTILS;
USE SCHEMA RETAIL_DWH.UTILS;

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1;

CREATE OR REPLACE STAGE MY_INTERNAL_STAGE
  FILE_FORMAT = MY_CSV_FORMAT;