USE SCHEMA RETAIL_DWH.STAGE;

CREATE OR REPLACE TABLE RAW_ORDERS (
    order_id VARCHAR,
    customer_id VARCHAR,
    status VARCHAR,
    order_date VARCHAR
);

CREATE OR REPLACE STREAM ORDERS_STREAM ON TABLE RAW_ORDERS;