USE DATABASE RETAIL_DWH;
USE SCHEMA CORE;

DROP PROCEDURE IF EXISTS PROCESS_ORDERS(); 

CREATE OR REPLACE PROCEDURE PROCESS_ORDERS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO RETAIL_DWH.CORE.DIM_ORDERS AS T
    USING (SELECT * FROM RETAIL_DWH.STAGE.ORDERS_STREAM) AS S
    ON T.order_id = S.order_id
    WHEN MATCHED THEN
        UPDATE SET T.status = S.status
    WHEN NOT MATCHED THEN
        INSERT (order_id, customer_id, status, order_date)
        VALUES (S.order_id, S.customer_id, S.status, TRY_TO_DATE(S.order_date));

    RETURN 'Success';
END;
$$;

GRANT USAGE ON PROCEDURE RETAIL_DWH.CORE.PROCESS_ORDERS() TO ROLE ACCOUNTADMIN;